### ISSUE TITLE
from train import data_produce, get_transition_from_data, get_smooth_transition

### ISSUE THREAD

**Issue by lufei576** [R0uter/LoginputEngine#2]
Traceback (most recent call last):
  File "D:\01AiDaShuAiGe\Project\LoginputEngine\main.py", line 3, in <module>
    from train import data_produce, get_transition_from_data, get_smooth_transition
ImportError: No module named train

下面是main.py代码
import tqdm
import os
from train import data_produce, get_transition_from_data, get_smooth_transition  这句话报错
import database_generator

如果我 pip install train 后，会出现其他更多错

不知道这个怎么解决了，求帮助

**Comment by lufei576** [comment]
这个问题是python版本的问题，我装了3.9.2这个版本就正常了

**Comment by R0uter** [comment]
ojbk
