### ISSUE TITLE
请教个问题：iOS上是使用本地离线的引擎还是云端引擎？

### ISSUE THREAD

**Issue by dongyuwei** [R0uter/LoginputEngine#4]
如题：如果是本地离线引擎，python代码是如何跑在iOS中的？云端的话感觉安全和隐私很难保证。

**Comment by R0uter** [comment]
这个仓库是落格输入法三维引擎的一个版本实现。使用python开源，主要还是为了方便大家学习算法实现。当然这个版本也可以用在桌面端实际生产环境当中。对于落格输入法来说，实际上是使用 Swift 语言进行重写以获取最高效率（iOS macOS），使用不同编程语言实现的完全相同的算法。另外我们也在开发 Android 端落格输入法，引擎则使用 Kotlin 进行重写。

---
所以回答你的问题：是本地离线引擎。python 开源仅供学习研究之用，落格输入法在各个平台使用原生语言进行原生实现。

**Comment by dongyuwei** [comment]
Thanks
